#!/usr/bin/env bash
# Install nginx, listen on port 80 and echo Hello world

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

chmod -R 7555 /var/www
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
