#!/usr/bin/env bash

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'
chmod -R 7555 /var/www

echo "Hello World!" > /var/www/index.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me
https://youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
