#!/usr/bin/env bash
# configure a brand new Ubuntu machine to task requirements

apt-get update
apt-get -y upgrade

apt-get -y install nginx
ufw allow 'Nginx HTTP'

mkdir -p /var/www/html


chmod -R 7555 /var/www
echo "Hello World!" > /var/www/html/index.html
echo "
	listen 80 default_server;
	listen [::]:80 default_server;

	add_header X-Served-By $HOSTNAME;
	root   /var/www/html;
	index index.html index.htm;

" > /etc/nginx/sites-available/default

service nginx start

