#!/usr/bin/env bash
# configure a brand new Ubuntu machine to task requirements

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chmod -R 7555 /var/www
sudo echo 'Hello World!' > /var/www/html/index.html
echo 'add_header X-Served-By $HOSTNAME' > /etc/nginx/nginx.conf
sudo service nginx start

