#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

apt-get -y update
apt-get -y upgrade

apt-get -y install --no-install-recommends software-properties-common

add-apt-repository ppa:vbernat/haproxy-2.6

apt-get install haproxy=2.6.\*

echo "
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 26071-web-01 34.229.56.207:80 check
    server 26071-web-02 52.91.127.250:80 check
" > /etc/haproxy/haproxy.cfg

service haproxy start
