#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# 9th iteration, displays Hi

i=1

while [ $i -lt "10" ]
do
    echo "Best School"

    if [ $i -eq "9" ]
    then
        echo "Hi"
        echo "Best School"
    fi

    ((i += 1))
done
