#!/usr/bin/env bash
# Loops from 1 to 10 and:
#   - display bad luck for the 4th iteration
#   - display good luck for the 8th iteration
#   - display Best School for other iterations

i=1

while [ $i -le "10" ]
do
    if [ $i -eq "4" ] ; then
        echo "bad luck"
    elif [ $i -eq "8" ] ; then
        echo "good luck"
    else
        echo "Best School"
    fi

    (("i += 1"))
done
