#!/usr/bin/env bash

# Displays numbers from 1 to 20
# Displays 4 and then bad luck from China for the 4th iteration
# Displays 9 and then bad luck from Japan for the 9th iteration
# Displays 17 and then bad luck from Italy for the 17th iteration
i=1

while [ $i -le "20" ]
do
    case $i in
        4)
            echo $i
            echo "bad luck from China"
            ;;
        9)
            echo $i
            echo "bad luck from Japan"
            ;;
        17)
            echo $i
            echo "bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac

    (("i += 1"))
done
